
package parts.gui;

import common.Database;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author: Taiybah Hussain EC15205
 * Reference List
 * 1. ManageUsersDialog.java : Used as an example for adding table models to JTables
 * 2. ManageUsersDialog.java : Used setLocationto(null) to centre dialog
 * 3. http://www.programcreek.com/java-api-examples/javax.swing.table.DefaultTableCellRenderer : Used to change JTable Layout
 * 4. http://stackoverflow.com/questions/3879610/how-to-clear-contents-of-a-jtable : Used to clear JTable
 * 5. LoginFrame.java : Used setTitle() to set a title to the dialog
 * 6. http://stackoverflow.com/questions/29123451/setmodal-method-on-a-jdialog: Used to set Modal
 */

public class partWithdrawal extends javax.swing.JDialog {

    /**
     * Creates new form PartWithdrawals
     */
    public partWithdrawal() {
        initComponents();
        this.withdrawalTable.setModel(TableModel);
        List <parts.logic.PartWithdrawals> ip;
        try {
            ip = Database.getInstance().getPartWithdrawalsOnly();
            for (parts.logic.PartWithdrawals pw: ip){
                    TableModel.addRow(pw);
                }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(this, "Error Getting Part Withdrawals");
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        leftRenderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
        withdrawalTable.getColumn("Booking ID").setCellRenderer(leftRenderer);
        withdrawalTable.getColumn("Quantity").setCellRenderer(leftRenderer);
        withdrawalTable.getColumn("Type").setCellRenderer(leftRenderer);
        withdrawalTable.getColumn("Booking ID").setMaxWidth(100);
        withdrawalTable.getColumn("Booking Date").setMinWidth(50);
        withdrawalTable.getColumn("Customer Name").setMinWidth(100);
        withdrawalTable.getColumn("Quantity").setMaxWidth(75);
    }
    private PartsWithdrawalTableModel TableModel = new PartsWithdrawalTableModel();
    
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        /**/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setTitle("Part Withdrawals");
        setModal(true);
        jScrollPane1 = new javax.swing.JScrollPane();
        withdrawalTable = new javax.swing.JTable();
        Done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        withdrawalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(withdrawalTable);

        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Done)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null); 
    }// </editor-fold>                        

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {                                     
        dispose();
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partWithdrawal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Done;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable withdrawalTable;
    // End of variables declaration                   
}
