package vehicles.gui;

import common.Database;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import vehicles.gui.TableModels.VehicleTemplatesTableModel;
import vehicles.logic.VehicleTemplate;

/**
 *
 * @author Akhil
 */
public class ManageVehicleTemplatePrompt extends javax.swing.JDialog {

    /**
     * Creates new form AddNewVehicleTemplate
     */
    public ManageVehicleTemplatePrompt() {
        initComponents();
        setModal(true);
        this.VehicleTemplatesTable.setModel(TableModel);
        TableModel.loadWarrantyDetails();
    }
    private final VehicleTemplatesTableModel TableModel = new VehicleTemplatesTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VehicleTemplatePane = new javax.swing.JScrollPane();
        VehicleTemplatesTable = new javax.swing.JTable();
        AddVehicleTemplate = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        setTitle("GMSIS / Manage Vehicle Templates");

        VehicleTemplatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        VehicleTemplatePane.setViewportView(VehicleTemplatesTable);

        AddVehicleTemplate.setText("Add");
        AddVehicleTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleTemplatePane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddVehicleTemplate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VehicleTemplatePane, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddVehicleTemplate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {
        AddVehTemp f = new AddVehTemp();
        f.show();
        if (f.isSuccessful()) {
            try {
                VehicleTemplate vt = f.parseVehicleTemplate();

                try {
                    // Add Vehicle Template to database and table
                    Database.getInstance().addVehicleTemp(vt);
                    TableModel.addRow(vt);
                    int lastRow = VehicleTemplatesTable.convertRowIndexToView(TableModel.getRowCount() - 1);
                    VehicleTemplatesTable.setRowSelectionInterval(lastRow, lastRow);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error adding Vehicle Template to the database.\r\n"
                            + "Error Message: " + e.getMessage(), "Add Vehicle Template // Database Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ParseException ex) {

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTemplatePrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTemplatePrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTemplatePrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTemplatePrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageVehicleTemplatePrompt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVehicleTemplate;
    private javax.swing.JScrollPane VehicleTemplatePane;
    private javax.swing.JTable VehicleTemplatesTable;
    // End of variables declaration//GEN-END:variables
}
