/**
 * Author ec15143 Nikita Miroyubov
 */
package specialist.gui;

import common.Database;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import specialist.gui.TableModels.SPCVehiclesAndCustomersTableModel;
import specialist.logic.SPC;

public class VehiclesAtSPCDetails extends javax.swing.JDialog {

    private final SPCVehiclesAndCustomersTableModel tableModel = new SPCVehiclesAndCustomersTableModel();
    private final SPC spc;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JScrollPane VehicleDetailsScrollPane;
    private javax.swing.JTable VehicleDetailsTable;
                    
    public VehiclesAtSPCDetails(SPC spc) {
        this.setModal(true);
        this.spc = spc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        this.setTitle("GMSIS SPC booking / Vehicles at selected center");
        VehicleDetailsScrollPane = new javax.swing.JScrollPane();
        VehicleDetailsTable = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableModel.loadVehicles(spc, "");
        VehicleDetailsTable.setModel(tableModel);
        VehicleDetailsScrollPane.setViewportView(VehicleDetailsTable);

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    SearchButtonActionPerformed(evt);
                } catch (SQLException | ParseException ex) {
                    Logger.getLogger(VehiclesAtSPCDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        SearchTextField.setText("reg.num/cust.name");
        SearchTextField.setForeground(Color.GRAY);
        SearchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTextFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(VehicleDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchButton)
                                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SearchButton)
                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addComponent(VehicleDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addContainerGap())
        );
        this.setPreferredSize(new Dimension(1500, 500));
        pack();
        this.setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ParseException {
        // TODO add your handling code here:
        tableModel.clearRows();
        tableModel.loadVehicles(spc, SearchTextField.getText());
        if (Database.getInstance().getAllVehiclesSentToSPC(spc, SearchTextField.getText()).isEmpty()) {
            tableModel.clearRows();
            tableModel.loadVehicles(spc, "");
            JOptionPane.showMessageDialog(null, "No vehicles found satisfying your criteria");

        } else {
            JOptionPane.showMessageDialog(null, tableModel.getRowCount() + " vehicle(s) found satisfying your criteria");
        }
    }

    private void SearchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {
        SearchTextField.setText("");
    }
                   
    
}
